language: php

php:
  - '5.6'

notifications:
  email: false
  
before_script:
  - php composer.phar require "codeception/codeception:*"
  - php ./vendor/bin/codecept bootstrap
  
script:
  php ./vendor/bin/codecept run