language: php

php:
  - '5.5'

notifications:
  email: false
  
services:
  - mysql
  
before_script:
  - wget http://codeception.com/codecept.phar
  - php codecept.phar bootstrap
  - mysql -u root -e 'create database bomberweb'
  - mysql -u root -e 'create table players(id int, gameroom int, x int, y int)' bomberweb
  
script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  #- sudo sed -i 's/always_populate_raw_post_data = 0/always_populate_raw_post_data = -1/g' ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  #- sudo echo "always_populate_raw_post_data = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo cat ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini | grep "always_populate_raw_post_data" 
  - sudo service apache2 restart
  - php codecept.phar build
  - php codecept.phar run tests/api/GetPidSuiteCest.php --steps --debug
  #- php codecept.phar run tests/api/GetPidCept.php --steps --debug
  #- php codecept.phar run tests/api/GetPidGetCept.php --steps --debug
  #- php codecept.phar run tests/api/GetPidPostBadHeaderCept.php --steps
  #- php codecept.phar run tests/api/GetPidPostNoActionCept.php --steps
  #- php codecept.phar run tests/api/GetPidPutCept.php --steps