language: php

php:
  - '5.6'

notifications:
  email: false
  
before_script:
  - wget http://codeception.com/codecept.phar
  - php codecept.phar bootstrap
  
script:
  - ls -lR
  - php codecept.phar run tests/api/GetPidCept.php