language: php

php:
  - '5.6'

notifications:
  email: false
  
before_script:
  - wget http://codeception.com/codecept.phar
  - php codecept.phar bootstrap
  
script:
  - pwd
  - curl -H "Content-Type: application/json" -X POST -d '{"action":"GetPid"}' http://localhost/api/v1/action/GetPid.php
  - php codecept.phar build
  - php codecept.phar run tests/api/GetPidCept.php --steps